The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [206]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!

In [207]:
df=pd.read_csv("data/nobel.csv")
df.head(4)

   year    category  ... death_city death_country
0  1901   Chemistry  ...     Berlin       Germany
1  1901  Literature  ...   Châtenay        France
2  1901    Medicine  ...    Marburg       Germany
3  1901       Peace  ...     Heiden   Switzerland

[4 rows x 18 columns]

## What is the most commonly awarded gender and birth country?

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  1000 non-null   int64
 1   category              1000 non-null   object
 2   prize                 1000 non-null   object
 3   motivation            912 non-null    object
 4   prize_share           1000 non-null   object
 5   laureate_id           1000 non-null   int64
 6   laureate_type         1000 non-null   object
 7   full_name             1000 non-null   object
 8   birth_date            968 non-null    object
 9   birth_city            964 non-null    object
 10  birth_country         969 non-null    object
 11  sex                   970 non-null    object
 12  organization_name     736 non-null    object
 13  organization_city     735 non-null    object
 14  organization_country  735 non-null    object
 15  death_date            596 non-null    object
 16  death_city            579 non-null    object
 17  death_country         585 non-null    object
dtypes: int64(2), object(16)
memory usage: 140.8+ KB

In [209]:
df['sex'].value_counts()

Male      905
Female     65
Name: sex, dtype: int64

In [210]:
df['birth_country'].value_counts()

United States of America                        291
United Kingdom                                   91
Germany                                          67
France                                           58
Sweden                                           30
                                               ...
Austria-Hungary (Ukraine)                         1
Ottoman Empire (Turkey)                           1
Russian Empire (Azerbaijan)                       1
Bosnia (Bosnia and Herzegovina)                   1
French protectorate of Tunisia (now Tunisia)      1
Name: birth_country, Length: 129, dtype: int64

In [211]:
top_gender='Male'
top_country='United States of America'

## Which decade had the highest ratio of US-born Nobel Prize winners to total winners in all categories?

In [212]:
US_winners=df[df['birth_country']==top_country]
year=US_winners.groupby('year').agg({'birth_country':'value_counts'})
year

                               birth_country
year birth_country
1906 United States of America              1
1912 United States of America              1
1914 United States of America              1
1919 United States of America              1
1923 United States of America              1
...                                      ...
2019 United States of America              3
2020 United States of America              7
2021 United States of America              2
2022 United States of America              6
2023 United States of America              3

[92 rows x 1 columns]

In [213]:
decades=[1900,1910,1920,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020]
decade_dictionary={}
for decade in decades:
    decade_dictionary[decade]=0
    
for year_country in year.index:
    year_value=year_country[0]
    number_of_winners=year.loc[(year_value,top_country),'birth_country']
    for decade in decades:
        in_decade= ( (year_value>decade) & (year_value<=decade+10) )
        if in_decade:
            decade_dictionary[decade]+=number_of_winners
            break
        else:
            continue
    
   
        
decade_dictionary

{1900: 1,
 1910: 3,
 1920: 5,
 1930: 13,
 1940: 16,
 1950: 20,
 1960: 22,
 1970: 36,
 1980: 33,
 1990: 39,
 2000: 50,
 2010: 42,
 2020: 11}

In [214]:
sorted(decade_dictionary.items(),key=lambda item: item[1],reverse=True)

[(2000, 50),
 (2010, 42),
 (1990, 39),
 (1970, 36),
 (1980, 33),
 (1960, 22),
 (1950, 20),
 (1940, 16),
 (1930, 13),
 (2020, 11),
 (1920, 5),
 (1910, 3),
 (1900, 1)]

In [215]:
max_decade_usa=2000

## Which decade and Nobel Prize category combination had the highest proportion of female laureates?

In [216]:
female=df[df['sex']=='Female']
category_year=female.groupby(['category','year']).agg({'sex':'value_counts'})

In [217]:
decade_dictionary={}
for decade in decades:
    decade_dictionary[decade]=0
    
category_year.index

MultiIndex([( 'Chemistry', 1911, 'Female'),
            ( 'Chemistry', 1935, 'Female'),
            ( 'Chemistry', 1964, 'Female'),
            ( 'Chemistry', 2009, 'Female'),
            ( 'Chemistry', 2018, 'Female'),
            ( 'Chemistry', 2020, 'Female'),
            ( 'Chemistry', 2022, 'Female'),
            ( 'Economics', 2009, 'Female'),
            ( 'Economics', 2019, 'Female'),
            ( 'Economics', 2023, 'Female'),
            ('Literature', 1909, 'Female'),
            ('Literature', 1926, 'Female'),
            ('Literature', 1928, 'Female'),
            ('Literature', 1938, 'Female'),
            ('Literature', 1945, 'Female'),
            ('Literature', 1966, 'Female'),
            ('Literature', 1991, 'Female'),
            ('Literature', 1993, 'Female'),
            ('Literature', 1996, 'Female'),
            ('Literature', 2004, 'Female'),
            ('Literature', 2007, 'Female'),
            ('Literature', 2009, 'Female'),
            ('Literature', 2013, 'Female'),
            ('Literature', 2015, 'Female'),
            ('Literature', 2018, 'Female'),
            ('Literature', 2020, 'Female'),
            ('Literature', 2022, 'Female'),
            (  'Medicine', 1947, 'Female'),
            (  'Medicine', 1977, 'Female'),
            (  'Medicine', 1983, 'Female'),
            (  'Medicine', 1986, 'Female'),
            (  'Medicine', 1988, 'Female'),
            (  'Medicine', 1995, 'Female'),
            (  'Medicine', 2004, 'Female'),
            (  'Medicine', 2008, 'Female'),
            (  'Medicine', 2009, 'Female'),
            (  'Medicine', 2014, 'Female'),
            (  'Medicine', 2015, 'Female'),
            (  'Medicine', 2023, 'Female'),
            (     'Peace', 1905, 'Female'),
            (     'Peace', 1931, 'Female'),
            (     'Peace', 1946, 'Female'),
            (     'Peace', 1976, 'Female'),
            (     'Peace', 1979, 'Female'),
            (     'Peace', 1982, 'Female'),
            (     'Peace', 1991, 'Female'),
            (     'Peace', 1992, 'Female'),
            (     'Peace', 1997, 'Female'),
            (     'Peace', 2003, 'Female'),
            (     'Peace', 2004, 'Female'),
            (     'Peace', 2011, 'Female'),
            (     'Peace', 2014, 'Female'),
            (     'Peace', 2018, 'Female'),
            (     'Peace', 2021, 'Female'),
            (     'Peace', 2023, 'Female'),
            (   'Physics', 1903, 'Female'),
            (   'Physics', 1963, 'Female'),
            (   'Physics', 2018, 'Female'),
            (   'Physics', 2020, 'Female'),
            (   'Physics', 2023, 'Female')],
           names=['category', 'year', 'sex'])

In [218]:
df['decade']=10*np.floor(df['year']/10)
df['decade']=df['decade'].astype(int)

In [219]:
df.head(4)

   year    category  ... death_country decade
0  1901   Chemistry  ...       Germany   1900
1  1901  Literature  ...        France   1900
2  1901    Medicine  ...       Germany   1900
3  1901       Peace  ...   Switzerland   1900

[4 rows x 19 columns]

In [220]:
df['female_winner']=df['sex']=='Female'

In [221]:
df.groupby(['category','decade'],as_index=False)['female_winner'].mean().max()

category         Physics
decade              2020
female_winner        0.5
dtype: object

In [222]:
max_female_dict={2020:'Literature'}

## Who was the first woman to receive a Nobel Prize, and in what category?

In [223]:
female.groupby(['year'],as_index=False).head(5)

     year    category  ...  death_city death_country
19   1903     Physics  ...  Sallanches        France
29   1905       Peace  ...      Vienna       Austria
51   1909  Literature  ...    Mårbacka        Sweden
62   1911   Chemistry  ...  Sallanches        France
128  1926  Literature  ...        Rome         Italy
..    ...         ...  ...         ...           ...
982  2022  Literature  ...         NaN           NaN
989  2023    Medicine  ...         NaN           NaN
993  2023     Physics  ...         NaN           NaN
998  2023       Peace  ...         NaN           NaN
999  2023   Economics  ...         NaN           NaN

[65 rows x 18 columns]

In [224]:
first_woman_name='Marie Curie, née Sklodowska'
first_woman_category='Physics'

## Which individuals or organizations have won more than one Nobel Prize throughout the years?

In [225]:
df['full_name'].value_counts()

Comité international de la Croix Rouge (International Committee of the Red Cross)    3
Linus Carl Pauling                                                                   2
John Bardeen                                                                         2
Frederick Sanger                                                                     2
Marie Curie, née Sklodowska                                                          2
                                                                                    ..
Karl Ziegler                                                                         1
Giulio Natta                                                                         1
Giorgos Seferis                                                                      1
Sir John Carew Eccles                                                                1
Claudia Goldin                                                                       1
Name: full_name, Length: 993, dtype: int64

In [226]:
repeat_list=[]
for index,count in df['full_name'].value_counts().items():
    if count>1:
        repeat_list.append(index)